### ISSUE TITLE
Intellisense is not working

### ISSUE THREAD

**Issue by lephamduythong** [OmniSharp/omnisharp-vscode#1595]
## Environment data
`dotnet --info` output:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

VS Code version: 1.13.1

C# Extension version: 1.10.0

## Steps to reproduce
dotnet new console
dotnet restore
open Program.cs file and the intellisense is not working.

Image:
![error](https://user-images.githubusercontent.com/22249338/27574499-d2dda246-5b40-11e7-9eac-a3082a646455.PNG)

## Expected  behavior
Show the intellisense.

**Comment by DustinCampbell** [comment]
Hi @lephamduythong. Thanks for the report! Could you copy and paste the full content of the OmniSharp log pictured in your screenshot?

**Comment by lephamduythong** [comment]
Here:

Starting OmniSharp server at 6/28/2017, 1:05:41 PM
    Target: c:\Users\ThongLee\Desktop\testDN

OmniSharp server started
    Path: C:\Users\ThongLee\.vscode\extensions\ms-vscode.csharp-1.10.0\bin\omnisharp\OmniSharp.exe
    PID: 14352

OmniSharp: -s c:\Users\ThongLee\Desktop\testDN --hostPID 13700 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'c:\Users\ThongLee\Desktop\testDN' on host 13700.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\ThongLee\Desktop\testDN
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[fail]: OmniSharp.Startup
        The project system 'OmniSharp.MSBuild.MSBuildProjectSystem' threw exception during initialization.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Build.Shared.VisualStudioLocationHelper.GetQuery()
   at Microsoft.Build.Shared.VisualStudioLocationHelper.GetInstances()
   at Microsoft.Build.Shared.BuildEnvironmentHelper.TryFromSetupApi()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OmniSharp.MSBuild.MSBuildHelpers.TryGetVisualStudioBuildEnvironment()
   at OmniSharp.MSBuild.MSBuildEnvironment.Initialize(ILogger logger)
   at OmniSharp.MSBuild.MSBuildProjectSystem.Initalize(IConfiguration configuration)
   at OmniSharp.Startup.InitializeWorkspace(OmniSharpWorkspace workspace, CompositionHost compositionHost, IConfiguration configuration, ILogger logger, OmniSharpOptions options)
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\ThongLee\Desktop\testDN'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.

**Comment by DustinCampbell** [comment]
@lephamduythong: Do you still have VS 2017 installed, or did you uninstall it at some point? If you have it installed, does it work?

@rainersigwald: Have you seen an error like this?

**Comment by lephamduythong** [comment]
Yes I still have VS 2017 installed in my PC and It doesn't work.
I reinstalled Windows 10 after my Windows 8 crashed. In Windows 8, I installed VS 2015, VS code worked fine with OmniSharp,.

**Comment by DustinCampbell** [comment]
Have you tried running a repair of VS 2017? OmniSharp will try and use the build environment from VS 2017 if it's installed, but it looks like the broken install is giving it fits.

**Comment by lephamduythong** [comment]
I have repaired and updated VS 2017 and it has been fixed, thanks very much

**Comment by DustinCampbell** [comment]
Glad to hear it!

**Comment by rainersigwald** [comment]
That's interesting. I haven't seen that error before. Glad a repair fixed it.

I don't know if it'd fix _this_, but I notice that we're using an old prerelease copy of the find-VS code; filed https://github.com/Microsoft/msbuild/issues/2251 to track updating to the latest.

**Comment by DustinCampbell** [comment]
@rainersigwald: FWIW, I don't think that would fix this issue. Looking at the exception, it looks to me like the COM component was registered but its DLL was missing on disk; i.e. a corrupted install.

**Comment by FomTarro** [comment]
I still have this issue, using VS Code on Win 10. I have used every manner of VS Uninstaller I can find to clean my registry, but to no avail.

```
System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at OmniSharp.MSBuild.Discovery.Interop.GetSetupConfiguration()
   at OmniSharp.MSBuild.Discovery.Providers.VisualStudioInstanceProvider.GetInstances()
   at OmniSharp.MSBuild.Discovery.MSBuildLocator.GetInstances()
   at OmniSharp.CompositionHostBuilder.RegisterMSBuildInstance(IMSBuildLocator msbuildLocator, ILogger logger)
   at OmniSharp.CompositionHostBuilder.Build()
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IConfiguration configuration, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource)
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at OmniSharp.HostHelpers.Start(Func`1 action)
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

**Comment by DustinCampbell** [comment]
@FomTarro: it looks to me like VS is still not fully installed. See the thread at https://github.com/OmniSharp/omnisharp-roslyn/issues/1219 for some solutions.
