### ISSUE TITLE
Test debugging does not work on .NET Core 2.0 and xUnit 2.3.0

### ISSUE THREAD

**Issue by anfomin** [OmniSharp/omnisharp-vscode#1733]
## Environment data
`dotnet --info` output:

```
Программы командной строки .NET (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version: 1.15.1
C# Extension version: 1.12.1
xUnit version: 2.3.0-beta4

## Steps to reproduce
Create project with any xUnit test and click codelens "debug test" button.

## Expected  behavior
Test should be runned in debug mode.

## Actual behavior
Exception message occurs:
`An exception occurred while test discoverer 'VsTestRunner' was loading tests. Exception: Object reference not set to an instance of an object.`

May be this is connected with this PR https://github.com/OmniSharp/omnisharp-roslyn/issues/944? If so then may you update extension to include this fix?

**Comment by DustinCampbell** [comment]
Yes, you're right that this was fixed recently in OmniSharp but that change has not made it into C# for VS Code yet. I'll keep this issue here until that happens and we have a new beta of C# for VS Code you can use.

**Comment by DustinCampbell** [comment]
I've just taken a new version of OmniSharp that fixes this and created a new beta release: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.13.0-beta1. You can following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to install the beta release.

**Comment by anfomin** [comment]
@DustinCampbell thank you!

**Comment by anfomin** [comment]
@DustinCampbell I've installed OmniSharp 1.13.0-beta1, but exception still appears on xUnit test debug:
`An exception occurred while test discoverer 'VsTestRunner' was loading tests. Exception: Object reference not set to an instance of an object.`

I'm using xUnit 2.3.0-beta5-build3769.

**Comment by DustinCampbell** [comment]
Oop! I forgot to merge in the C# for VS Code side of this fix before creating the new beta. Will fix shortly.

**Comment by DustinCampbell** [comment]
New day, new release. Please try C# for VS Code 1.13.0-beta2: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/1.13.0-beta2.

**Comment by fletchsod-developer** [comment]
Got this error with the VS-Code version (Sept 2017).  :-/

9/25/2017 10:52:14 AM - Microsoft VSIX Installer
9/25/2017 10:52:14 AM - -------------------------------------------
9/25/2017 10:52:14 AM - Initializing Install...
9/25/2017 10:52:14 AM - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__11_1(String s)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream, String localeRelativeRoot, Boolean localize)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream vsixStream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by leechen** [comment]
I still got the same error message after installed the vsix manually (1.13.0-beta2):

> An exception occurred while test discoverer 'VsTestRunner' was loading tests. Exception: Object reference not set to an instance of an object.
> Debugging complete.

**Comment by leechen** [comment]
Might be related with the "Reload" icon. I did reload multiple times. Not sure why it is still there.

<img width="534" alt="screen shot 2017-10-13 at 4 26 13 pm" src="https://user-images.githubusercontent.com/3713000/31565065-684527cc-b033-11e7-8c4f-4ac2ec085433.png">

**Comment by leechen** [comment]
After uninstall 1.13.0-beta2 and reinstall manually, the "reload" icon is finally gone. The debug is working now.

**Comment by DustinCampbell** [comment]
Glad to hear it's working for you now.

**Comment by johnnyreilly** [comment]
Just discovered this - I'm managing to debug in VS Code now :champagne: Do you happen to know when this might be released?

**Comment by DustinCampbell** [comment]
We're aiming for a release by the end of the month.

**Comment by johnnyreilly** [comment]
Sweet - thanks!

**Comment by wadinj** [comment]
Great thread ! After 2 hours of googling I finally found it ! Thanks @DustinCampbell for the fix

**Comment by americofreitasjr** [comment]
I'm having the same problem in vs-code on Ubuntu. Has this also been resolved? Thank you. See @asilferreira.

**Option "debug test"**
![image](https://user-images.githubusercontent.com/11709838/32255928-e059da9c-be92-11e7-9c5b-9b5a913eba3e.png)


**Error:**
An exception occurred while test discoverer 'VsTestRunner' was loading tests. Exception: Object reference not set to an instance of an object.

**Info:**
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by DustinCampbell** [comment]
@americofreitasjr: Have you tried the latest C# for VS Code [1.13-beta5 release](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.13.0-beta5)? You can follow the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to install a beta release.
