### ISSUE TITLE
Can't attach debugger when running on Cloud Foundry

### ISSUE THREAD

**Issue by macsux** [OmniSharp/omnisharp-vscode#2603]
## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    7fa21d645b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /home/vcap/deps/0/dotnet-sdk/sdk/2.1.402/

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.402 [/home/vcap/deps/0/dotnet-sdk/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [/home/vcap/deps/0/dotnet-sdk/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [/home/vcap/deps/0/dotnet-sdk/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [/home/vcap/deps/0/dotnet-sdk/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
VS Code version:
1.28.1
C# Extension version:
1.16.2
## Steps to reproduce
Use any Cloud Foundry foundation (PAS). The easiest way to test is to get PWS account at run.pivotal.io
1. Install CF CLI https://docs.cloudfoundry.org/cf-cli/install-go-cli.html
2. Login to PCF `cf login -a api.run.pivotal.io`
3. Publish any .net core 2.1 app `dotnet publish`
4. CD into the publish folder and push on to the platform `cf push myappname`
5. Install vsdbg into container 
5.1. `cf ssh myappname`
5.2 `curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg`
6. Create launch file as per following
```
{
  "name": ".NET Core Remote Attach",
  "configurations": [
    {
      "name": ".NET Core Attach",
      "type": "coreclr",
      "request": "attach",
      "processName": "dotnet",
      "pipeTransport": {
        "pipeCwd": "${workspaceFolder}",
        "pipeProgram": "c:\\tools\\putty\\plink.exe",
        "pipeArgs": [ 
          "-l", "cf:7d051231-35d7-4e2b-941c-0b02ca385909/0", 
          "-pw", "TNt2bUZbxr", 
          "ssh.run.pivotal.io",
          "-P", "2222", 
          "-hostkey", "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
          "-batch",
          "-T" ],
        "logging": {
            "engineLogging": true
        },
        "debuggerPath": "~/vsdbg/vsdbg"
      }
    }
  ],
  
}
```
6.1. Adjust pipeProgram to point to plink (part of putty package)
6.2. Use `cf app myappname --guid` and use output to fix up pipeArgs for username `-l` parameter "cf:7d051231-35d7-4e2b-941c-0b02ca385909/0". Guid is in middle, prefix must be `cf:` and sufix `/0`
6.3. Get one time ssh password `cf ssh-code` and plug it into launchArgs for -pw arg

## Expected  behavior
Debugger attaches successfully

## Actual behavior
Failed to debug. See output below (captured out of Visual Studio, but result is the same in VS Code as well)
```
<- (E) {"seq":2,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"attach"}
<- (E) {"seq":6,"type":"event","event":"initialized","body":{}}
-> (C) {"request_seq":1,"success":true,"command":"handshake","body":{"signature":"0501Nv6+lxTvkiufXJnmv4i2am/48NQ+jl8FCBa0LaQybs="},"seq":3,"type":"response"}
-> (C) {"command":"setDebuggerProperty","arguments":{"DisableJITOptimization":0},"seq":4,"type":"request"}
<- (R) {"seq":10,"type":"response","request_seq":4,"success":true,"command":"setDebuggerProperty","message":"","body":{}}
-> (C) {"command":"setDebuggerProperty","arguments":{"InterpreterOptions":1},"seq":5,"type":"request"}
<- (R) {"seq":13,"type":"response","request_seq":5,"success":true,"command":"setDebuggerProperty","message":"","body":{}}
-> (C) {"command":"setDebuggerProperty","arguments":{"JustMyCodeStepping":1},"seq":6,"type":"request"}
<- (R) {"seq":16,"type":"response","request_seq":6,"success":true,"command":"setDebuggerProperty","message":"","body":{}}
-> (C) {"command":"setDebuggerProperty","arguments":{"StopOnExceptionCrossingManagedBoundary":0},"seq":7,"type":"request"}
<- (R) {"seq":19,"type":"response","request_seq":7,"success":true,"command":"setDebuggerProperty","message":"","body":{}}
-> (C) {"command":"setDebuggerProperty","arguments":{"WarnIfNoUserCodeOnLaunch":1},"seq":8,"type":"request"}
<- (R) {"seq":22,"type":"response","request_seq":8,"success":true,"command":"setDebuggerProperty","message":"","body":{}}
-> (C) {"command":"setDebuggerProperty","arguments":{"EnableStepFiltering":true},"seq":9,"type":"request"}
<- (R) {"seq":25,"type":"response","request_seq":9,"success":true,"command":"setDebuggerProperty","message":"","body":{}}
-> (C) {"command":"setSymbolOptions","arguments":{"symbolOptions":{"searchPaths":[""],"cachePath":"","moduleFilter":{"mode":"loadAllButExcluded","excludedModules":[""]}}},"seq":10,"type":"request"}
<- (R) {"seq":28,"type":"response","request_seq":10,"success":true,"command":"setSymbolOptions"}
-> (C) {"command":"setBreakpoints","arguments":{"source":{"path":"c:\\projects\\pcf-ers-dotnetcore-demo\\src\\Controllers\\HomeController.cs","sources":[],"checksums":[{"algorithm":"MD5","checksum":"8f3635ab9d90bad14faecd6d128895fa"},{"algorithm":"MD5","checksum":"a1e50e931fe59c701ecae6588763c49b"},{"algorithm":"SHA1","checksum":"77b2464865d8e40fe836950b9617174259a6db9d"},{"algorithm":"SHA1","checksum":"622107161a66a6686039efca108821c844e43d53"},{"algorithm":"SHA256","checksum":"d18dbd0c70177f1697ffe1bcd9ba4a5887b9099bde39f3cb00da5b88637a92cb"},{"algorithm":"SHA256","checksum":"a47bea88dc719dc6d28ec38d97220b8dadee52eafc02393f3f92d902000a3987"}]},"breakpoints":[{"line":23,"column":13}],"lines":[23]},"seq":11,"type":"request"}
<- (R) {"seq":31,"type":"response","request_seq":11,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":1,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":23,"column":13}]}}
-> (C) {"command":"setBreakpoints","arguments":{"source":{"path":"c:\\projects\\pcf-ers-dotnetcore-demo\\src\\Controllers\\HomeController.cs","sources":[],"checksums":[{"algorithm":"MD5","checksum":"8f3635ab9d90bad14faecd6d128895fa"},{"algorithm":"MD5","checksum":"a1e50e931fe59c701ecae6588763c49b"},{"algorithm":"SHA1","checksum":"77b2464865d8e40fe836950b9617174259a6db9d"},{"algorithm":"SHA1","checksum":"622107161a66a6686039efca108821c844e43d53"},{"algorithm":"SHA256","checksum":"d18dbd0c70177f1697ffe1bcd9ba4a5887b9099bde39f3cb00da5b88637a92cb"},{"algorithm":"SHA256","checksum":"a47bea88dc719dc6d28ec38d97220b8dadee52eafc02393f3f92d902000a3987"}]},"breakpoints":[{"line":23,"column":13}],"lines":[23]},"seq":12,"type":"request"}
<- (R) {"seq":34,"type":"response","request_seq":12,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":1,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":23,"column":13}]}}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":[],"exceptionOptions":[{"path":[{"names":["CLR"]}],"breakMode":"userUnhandled"},{"path":[{"names":["CLR"]},{"names":["System.AppDomainUnloadedException","System.Threading.ThreadAbortException"]}],"breakMode":"unhandled"},{"path":[{"names":["CLR"]},{"names":["System.Windows.Markup.XamlParseException","System.Reflection.MissingMetadataException","System.Reflection.MissingRuntimeArtifactException"]}],"breakMode":"always"},{"path":[{"names":["MDA"]}],"breakMode":"unhandled"},{"path":[{"names":["MDA"]},{"names":["CallbackOnCollectedDelegate","ContextSwitchDeadlock","DateTimeInvalidLocalFormat","DisconnectedContext","FatalExecutionEngineError","InvalidFunctionPointerInDelegate","InvalidMemberDeclaration","InvalidVariant","LoaderLock","NonComVisibleBaseClass","PInvokeStackImbalance","RaceOnRCWCleanup","Reentrancy"]}],"breakMode":"always"}]},"seq":13,"type":"request"}
<- (R) {"seq":37,"type":"response","request_seq":13,"success":true,"command":"setExceptionBreakpoints"}
-> (C) {"command":"configurationDone","arguments":{},"seq":14,"type":"request"}
<- (E) {"seq":40,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/AttachFailed","data":{"VS.Diagnostics.Debugger.vsdbg.ErrorCode":-2146231288,"VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"ubuntu","VS.Diagnostics.Debugger.vsdbg.Distribution.Version":"14.04","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.Version":"15.7.20426.1 commit:91b285752d1135b8cdcdb3d74b44ca9faee48809"}}}
<- (R) {"seq":42,"type":"response","request_seq":14,"success":false,"command":"configurationDone","message":"Failed to attach to process: Unknown Error: 0x80131c08"}
```

**Comment by tremblaysimon** [comment]
Hello, 

using 

.NET Core 2.1.402
VS Code 1.28.2
C# extension 1.17.0

vsdbg including libunwind (manually inserted like you did)

and cf ssh instead of plink, 

```
{
    "name": ".NET Core Remote Attach",
    "configurations": [
      {
        "name": ".NET Core Attach",
        "type": "coreclr",
        "request": "attach",
        "processName": "dotnet",
        "pipeTransport": {
          "pipeCwd": "${workspaceFolder}",
          "pipeProgram": "cf",
          "pipeArgs": [
            "ssh", "APP_NAME",
            "-c" ],
          "logging": {
              "engineLogging": true
          },
          "debuggerPath": "~/app/vsdbg/vsdbg"
        }
      }
    ],
}
```

remote debugging is working well here.

**Comment by macsux** [comment]
Can you please outline steps you took to install libunwind. I think this is the part I was missing. I tried introducing it, I'm no longer getting same error, but it still disconnects from debugging session.

`<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"attach"}
<- (E) {"seq":6,"type":"event","event":"initialized","body":{}}
-> (C) {"request_seq":1,"success":true,"command":"handshake","body":{"signature":"249Q2/rp+7WnbPLb+UkgCUiGm28N8l1/5xUa2XnkhKdjcE="},"seq":3,"type":"response"}
-> (C) {"command":"setDebuggerProperty","arguments":{"DisableJITOptimization":0},"seq":4,"type":"request"}
<- (R) {"seq":10,"type":"response","request_seq":4,"success":true,"command":"setDebuggerProperty","message":"","body":{}}
-> (C) {"command":"setDebuggerProperty","arguments":{"InterpreterOptions":1},"seq":5,"type":"request"}
<- (R) {"seq":13,"type":"response","request_seq":5,"success":true,"command":"setDebuggerProperty","message":"","body":{}}
-> (C) {"command":"setDebuggerProperty","arguments":{"JustMyCodeStepping":1},"seq":6,"type":"request"}
<- (R) {"seq":16,"type":"response","request_seq":6,"success":true,"command":"setDebuggerProperty","message":"","body":{}}
-> (C) {"command":"setDebuggerProperty","arguments":{"StopOnExceptionCrossingManagedBoundary":0},"seq":7,"type":"request"}
<- (R) {"seq":19,"type":"response","request_seq":7,"success":true,"command":"setDebuggerProperty","message":"","body":{}}
-> (C) {"command":"setDebuggerProperty","arguments":{"WarnIfNoUserCodeOnLaunch":1},"seq":8,"type":"request"}
<- (R) {"seq":22,"type":"response","request_seq":8,"success":true,"command":"setDebuggerProperty","message":"","body":{}}
-> (C) {"command":"setDebuggerProperty","arguments":{"EnableStepFiltering":true},"seq":9,"type":"request"}
<- (R) {"seq":25,"type":"response","request_seq":9,"success":true,"command":"setDebuggerProperty","message":"","body":{}}
-> (C) {"command":"setSymbolOptions","arguments":{"symbolOptions":{"searchPaths":[""],"cachePath":"","moduleFilter":{"mode":"loadAllButExcluded","excludedModules":[""]}}},"seq":10,"type":"request"}
<- (R) {"seq":28,"type":"response","request_seq":10,"success":true,"command":"setSymbolOptions"}
-> (C) {"command":"setBreakpoints","arguments":{"source":{"path":"c:\\projects\\pcf-ers-dotnetcore-demo\\src\\Controllers\\HomeController.cs","sources":[],"checksums":[{"algorithm":"MD5","checksum":"8f3635ab9d90bad14faecd6d128895fa"},{"algorithm":"MD5","checksum":"a1e50e931fe59c701ecae6588763c49b"},{"algorithm":"SHA1","checksum":"77b2464865d8e40fe836950b9617174259a6db9d"},{"algorithm":"SHA1","checksum":"622107161a66a6686039efca108821c844e43d53"},{"algorithm":"SHA256","checksum":"d18dbd0c70177f1697ffe1bcd9ba4a5887b9099bde39f3cb00da5b88637a92cb"},{"algorithm":"SHA256","checksum":"a47bea88dc719dc6d28ec38d97220b8dadee52eafc02393f3f92d902000a3987"}]},"breakpoints":[{"line":23,"column":13}],"lines":[23]},"seq":11,"type":"request"}
<- (R) {"seq":31,"type":"response","request_seq":11,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":1,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":23,"column":13}]}}
-> (C) {"command":"setBreakpoints","arguments":{"source":{"path":"c:\\projects\\pcf-ers-dotnetcore-demo\\src\\Controllers\\HomeController.cs","sources":[],"checksums":[{"algorithm":"MD5","checksum":"8f3635ab9d90bad14faecd6d128895fa"},{"algorithm":"MD5","checksum":"a1e50e931fe59c701ecae6588763c49b"},{"algorithm":"SHA1","checksum":"77b2464865d8e40fe836950b9617174259a6db9d"},{"algorithm":"SHA1","checksum":"622107161a66a6686039efca108821c844e43d53"},{"algorithm":"SHA256","checksum":"d18dbd0c70177f1697ffe1bcd9ba4a5887b9099bde39f3cb00da5b88637a92cb"},{"algorithm":"SHA256","checksum":"a47bea88dc719dc6d28ec38d97220b8dadee52eafc02393f3f92d902000a3987"}]},"breakpoints":[{"line":23,"column":13}],"lines":[23]},"seq":12,"type":"request"}
<- (R) {"seq":34,"type":"response","request_seq":12,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":1,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":23,"column":13}]}}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":[],"exceptionOptions":[{"path":[{"names":["CLR"]}],"breakMode":"userUnhandled"},{"path":[{"names":["CLR"]},{"names":["System.AppDomainUnloadedException","System.Threading.ThreadAbortException"]}],"breakMode":"unhandled"},{"path":[{"names":["CLR"]},{"names":["System.Windows.Markup.XamlParseException","System.Reflection.MissingMetadataException","System.Reflection.MissingRuntimeArtifactException"]}],"breakMode":"always"},{"path":[{"names":["MDA"]}],"breakMode":"unhandled"},{"path":[{"names":["MDA"]},{"names":["CallbackOnCollectedDelegate","ContextSwitchDeadlock","DateTimeInvalidLocalFormat","DisconnectedContext","FatalExecutionEngineError","InvalidFunctionPointerInDelegate","InvalidMemberDeclaration","InvalidVariant","LoaderLock","NonComVisibleBaseClass","PInvokeStackImbalance","RaceOnRCWCleanup","Reentrancy"]}],"breakMode":"always"}]},"seq":13,"type":"request"}
<- (R) {"seq":37,"type":"response","request_seq":13,"success":true,"command":"setExceptionBreakpoints"}
-> (C) {"command":"configurationDone","arguments":{},"seq":14,"type":"request"}`

**Comment by tremblaysimon** [comment]
1. I downloaded vsdbg and put it directly in my publish folder before cf push the app

2. Put libunwind in the vsdbg folder from that deb file here: http://archive.ubuntu.com/ubuntu/pool/main/libu/libunwind/libunwind8_1.1-2.2ubuntu3_amd64.deb

2.1 I extracted the .deb file and put all files (and symlinks) from data/usr/lib/x86_64-linux-gnu into vsdbg folder (like libunwind.so.8, libunwind.so.8.0.1, libunwind-coredump.so.0, etc.)

3. I did a cf push of my publish folder

4. Started the VS Code debugger (with the launch.json in my .vscode folder like my previous comment, APP_NAME replaced by my app name in PCF)

**Comment by macsux** [comment]
I was doing exactly what you wrote before, and it's not working for me - tired in both VSCode & Visual Studio. Which OS are you on? I'm on Windows 10, tried on two separate machines.

**Comment by tremblaysimon** [comment]
I'm on Ubuntu 18.04. I don't have any machine on Windows 10, I will try on Windows 7 to see if it's working as expected.

**Comment by gregg-miskelly** [comment]
There is nearly zero chance that the error you are running into has anything to do with the client OS.

What would matter a great deal:
* What version of CoreCLR the target app is running on (the failure is from the CoreCLR debugging services)
* The server OS

**Comment by gregg-miskelly** [comment]
In case it is helpful, the failure is CORDBG_E_TIMEOUT. Here are the places where CoreCLR might return that error: https://github.com/dotnet/coreclr/search?q=CORDBG_E_TIMEOUT&unscoped_q=CORDBG_E_TIMEOUT

**Comment by macsux** [comment]
The sample app I'm trying is targeting 2.1 and the buildpack is introducing dotnetcore runtime version 2.1.4

**Comment by tremblaysimon** [comment]
My server OS is on Ubuntu 14.04. Are you getting the right libunwind package? For Xenial it seems to be that one: http://archive.ubuntu.com/ubuntu/pool/main/libu/libunwind/libunwind_1.1-4.1.debian.tar.xz (took from https://packages.ubuntu.com/xenial/libunwind8)

**Comment by macsux** [comment]
So this is interesting - my colleague on a Mac just tried this and it worked for him. I gave him the exact vsdbg folder that I created with libunwind inside that I used when I pushed my code. I'm getting my hands on his exact project that he pushed to see if that accounts for the difference.

**Comment by tremblaysimon** [comment]
Finally I've got the same problem here. I figured out that my target framework was netcoreapp2.0 instead of netcoreapp2.1. When target framework is netcoreapp2.1, I get same error as you. If I launch vsdbg manually from the container, with that properties in my csproj: 

```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
...
  </PropertyGroup>
```
I get that error: 

```
vcap@972edef1-d929-493d-4f86-5865:~/app/vsdbg$ ./vsdbg --attach 49
Unable to attach to process 49. Unknown Error: 0x80131c08
Segmentation fault (core dumped)

```
If I use 2.0 like this in my csproj: 

```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
...
  </PropertyGroup>
```
it works perfectly as expected:
```
vcap@a659ee19-0fd7-400b-7ba1-ea90:~/app/vsdbg$ ./vsdbg --attach 51
=telemetry,event-name="VS/Diagnostics/Debugger/vsdbg/ProcessCreate",properties={VS.Diagnostics.Debugger.vsdbg.Version="15.7.20426.1 commit:91b285752d1135b8cdcdb3d74b44ca9faee48809",VS.Diagnostics.Debugger.vsdbg.OSFamily="Linux",VS.Diagnostics.Debugger.vsdbg.Distribution.Name="ubuntu",VS.Diagnostics.Debugger.vsdbg.Distribution.Version="14.04"}
=message,text="--------------------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with Visual Studio\nCode, Visual Studio or Visual Studio for Mac software to help you develop and\ntest your applications.\n--------------------------------------------------------------------------------\n",send-to="output-window"
(gdb)
=telemetry,event-name="VS/Diagnostics/Debugger/vsdbg/TargetRuntimeLoaded",properties={VS.Diagnostics.Debugger.vsdbg.TargetRuntimeVersion.MS="Unknown",VS.Diagnostics.Debugger.vsdbg.TargetRuntimeVersion.LS="Unknown",VS.Diagnostics.Debugger.vsdbg.Version="15.7.20426.1 commit:91b285752d1135b8cdcdb3d74b44ca9faee48809",VS.Diagnostics.Debugger.vsdbg.OSFamily="Linux",VS.Diagnostics.Debugger.vsdbg.Distribution.Name="ubuntu",VS.Diagnostics.Debugger.vsdbg.Distribution.Version="14.04"}
```

**Comment by tremblaysimon** [comment]
Info: It's working to debug on a Ubuntu 14.04 docker container which I installed .NET Core 2.1, vsdbg and my app. 

What is interesting with PCF, if I run /tmp/lifecycle/shell before executing vsdbg, it's working with an app that target 2.1...

**Comment by gregg-miskelly** [comment]
I don't know how likely this is to actually help, but you might double check that this issue isn't resolved using the new beta release of vsdbg.

To try the beta, follow instruction from [the wiki](https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-processes), but instead of obtaining vsdbg using `https://aka.ms/getvsdbgsh` instead use `https://aka.ms/getvsdbgshbeta` (or replace 'sh' with 'ps1' if you want the powershell version of the script).

**Comment by tremblaysimon** [comment]
Thank you for that hint, but I get the same error even with the beta version of vsdbg. 

I don't know if @macsux could provide more information about what does /tmp/lifecycle/shell command in PCF (other than setting new environment variables) since vsdbg attach properly when that command is executed. 

Sadly I can't figure out how to plug that "shell" command in launch.json and I don't think it's a good idea in the end...

**Comment by macsux** [comment]
Ok, I've figured it out. /tmp/lifecycle/shell sets up the environment as it should be for running the app. the issue is how to execute it as part of launch.json. The syntax for launch.json is different between VSCode & Visual Studio. The following allows me to debug from within visual studio:

```
{
  "version": "0.2.0",
  "adapter": "cf",
  "adapterArgs": "ssh democore -c \"/tmp/lifecycle/shell /home/vcap/app 'bash -c \\\"~/vsdbg/vsdbg --interpreter=vscode\\\"'\"",
  "languageMappings": {
    "C#": {
      "languageId": "3F5162F8-07C6-11D3-9053-00C04FA302A1",
      "extensions": [ "*" ]
    }
  },
  "exceptionCategoryMappings": {
    "CLR": "449EC4CC-30D2-4032-9256-EE18EB41B62B",
    "MDA": "6ECE07A9-0EDE-45C4-8296-818D8FC401D4"
  },
  "configurations": [
    {
      "name": ".NET Core Launch",
      "type": "coreclr",
      "processName": "dotnet",
      "request": "attach",
      "justMyCode": false,
      "cwd": "~/app",
      "logging": {
        "engineLogging": true
      }
    }
  ]
}
```

The problem is that for VSCode, we pass in the args via `pipeArgs` which appends the debugger path on the end. Given that how it needs to be executed as part of this launch command, VSCode's syntax isn't flexible enough for the debugger launch command to be inserted in the middle of a command that actually needs to be executed (at least I haven't found a way - maybe someone else can chime in).

**Comment by tremblaysimon** [comment]
I agree that libunwind is added by the buildpack. But not in the /lib folder. It is added in the /home/vcap/deps/ folder so the LD_LIBRARY_PATH must be set (which is done by /tmp/lifecycle/shell command). 

I don't understand yet why there is this different behavior in PCF (vsdbg attach to an app) between .NET Core 2.1 vs 2.0...

**Comment by macsux** [comment]
Ok, I've figured out how to do this with VSCode now:

```
{
    "name": ".NET Core Remote Attach",
    "configurations": [
      {
        "name": ".NET Core Attach",
        "type": "coreclr",
        "request": "attach",
        "processName": "dotnet",
        "pipeTransport": {
          "pipeCwd": "${workspaceFolder}",
          "pipeProgram": "cf",
          "pipeArgs": [
            "ssh", "democore", "-c", "\"/tmp/lifecycle/shell /home/vcap/app 'bash -c \\\"${debuggerCommand}\\\"'\"" ],
          "logging": {
              "engineLogging": true
          },
          "debuggerPath": "~/vsdbg/vsdbg"
        }
      }
    ],
}
```

**Comment by macsux** [comment]
Summary on how to get this working on Cloud Foundry: https://dotnet-cookbook.cfapps.io/core/remote-debug/
