### ISSUE TITLE
Unable to resolve assembly for Unity

### ISSUE THREAD

**Issue by Cinabutts** [OmniSharp/omnisharp-vscode#2725]
Before I start let me just tell you I have no idea what is going on here lmao
I'm fairly new to code and this is more of a hobby but anyway reading threw a similar issue posted(Not relevant because they were on osx) what i'm thinking is OmniSharp is looking for Assembly-CSharp-firstpass.dll in the wrong place, I don't know why but I guess Unity put the file into `C:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Library\ScriptAssemblies` soo yeah that's all I know.

## Environment data
`dotnet --info` output: 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

VS Code version: 1.29.1.
C# Extension version: 1.17.1

## Steps to reproduce
no idea

## Expected  behavior
no warnings/errors?

## Actual behavior

**OmniSharp Output log:**
```
> Starting OmniSharp server at 12/1/2018, 6:55:36 AM
    Target: c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Fresh Start.sln

OmniSharp server started.
    Path: C:\Users\koolj\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe
    PID: 9784

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.9.28307.145 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\koolj\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2017 15.9.28307.145 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Fresh Start.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp-Editor-firstpass.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start' on host 10064.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp-firstpass.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp-firstpass.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp-Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp-Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp-Editor-firstpass.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp-Editor-firstpass.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Assembly-CSharp-Editor-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Temp\bin\Debug\Assembly-CSharp-firstpass.dll'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-firstpass
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Temp\bin\Debug\Assembly-CSharp-Editor-firstpass.dll'
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Temp\bin\Debug\Assembly-CSharp-firstpass.dll'
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Temp\bin\Debug\Assembly-CSharp.dll'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor-firstpass
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly 'c:\Users\koolj\Documents\Unity Projects\_TEST-PROJECTS\Fresh Start\Temp\bin\Debug\Assembly-CSharp-firstpass.dll'
```

**Comment by rchande** [comment]
@Cinabutts Are you having any problems working with your code? Eg, no intellisense, etc? These warnings may be benign...

**Comment by Cinabutts** [comment]
Okay so just created a brand new fresh Unity project and loaded the vs project and it worked perfectly, So it must be something to do with Unity

**Comment by akshita31** [comment]
@Cinabutts Is there anything that you think should be fixed here . Otherwise we could close this issue.

**Comment by Cinabutts** [comment]
Well I'm not sure because if it isn't obvious enough I'm no where near experienced in this. There is an issue with either Unity or vs code/ Omnisharp I just don't know what it is hints the reason why I created this issue in the first place. So until I get even a clue on what's going on with this issue I'd appreciate the issue remain open. I'll soon create a post on Unity regarding the issue in hopes that they'll know a little more about it but I made the post here assuming Unity devs are more like me and just wanted to open up vs code and assume everything was workingcorrectly. If you think YOU can provide any solution to this issue than let me know. There clearly isn't that much to work with regarding my issue so if you need anything ie logs, project folders and how it's laid out or just some pictures again let me know.

**Comment by Cinabutts** [comment]
So i've just decided to create an entire new project and copy paste my entire asset folder into the new one, I think what happened is I didn't properly install .net sdk or something, i honestly don't remember what it is but it was working fine without that before but i never actually had the time to actually script anything as much. Anyway i'm closing this now.
