### ISSUE TITLE
Code Intellisense not Working when using Vastest versions.

### ISSUE THREAD

**Issue by mdmoura** [OmniSharp/omnisharp-vscode#3037]
## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.2.104 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

VS Code version: 1.33.1
C# Extension version: 1.19.0

## Steps to reproduce
I have a visual studio code workspace with 4 projects ...
On the status bar I can see a green flame with the tooltip "Omisharp server is running"

I can restart Omnisharp and change to another project ...
But next to the Omnisharp flame icon there is no project name.

## Expected  behavior
I would expect code intellisense as it did before with exactly the same projects and workspace.

## Actual behavior

When I open a C# file I can see references count on top of each method.
But I do not have code intellisense ... Any idea what is going on?
I already reinstalled all extensions and Visual Studio Code ...
But after I reinstalled everything the result is the same.

**Comment by DagHalfvild** [comment]
Have the same issue here, no more references, no more warnings when errors, no minimap (enabled in both user/workspace settings)... Everything works perfectly with native languages, but not with C#...

**Comment by akshita31** [comment]
@mdmoura Can you share your 
Please paste the output from your [OmniSharp log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Reporting-Issues#omnisharp-and-c-log) using `Ctrl+Shift+F9` that would show the log window?

**Comment by mdmoura** [comment]
@akshita31 Sure, here it is the log when I restart OmniSharp:

```
Starting OmniSharp server at 5/2/2019, 10:06:57 PM
    Target: /Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api

OmniSharp server started with Mono 5.18.1.
    Path: /Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/OmniSharp.exe
    PID: 1712

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api/MvcProj.Api.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api' on host 1067.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api/MvcProj.Api.csproj
```

Any idea what is going on?

**Comment by akshita31** [comment]
Could you try setting "omnisharp.loglevel" --> debug and restart omnisharp ?

**Comment by mdmoura** [comment]
@akshita31 Sure, here it is:

Starting OmniSharp server at 5/2/2019, 10:14:44 PM
    Target: /Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api

OmniSharp server started with Mono 5.18.1.
    Path: /Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/OmniSharp.exe
    PID: 1758

[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Cake, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.DotNet, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.DotNetTest, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Host, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.MSBuild, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Roslyn, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Roslyn.CSharp, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Script, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Shared, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin"
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.Build.Utilities.Core.dll' (name-only).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.Build.Tasks.Core.dll' (name-only).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.Build.Framework.dll' (name-only).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.Build.dll' (name-only).
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.CodeAnalysis.VisualBasic.Workspaces, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll'.
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.CodeAnalysis.VisualBasic.Features, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.CodeAnalysis.VisualBasic.Features.dll'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[dbug]: OmniSharp.MSBuild.ProjectSystem
        MSBuild environment: 
Mode: Standalone
RunningTests: False
RunningInVisualStudio: False
MSBuildToolsDirectory32: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin
MSBuildToolsDirectory64: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin
MSBuildSDKsPath: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks
CurrentMSBuildConfigurationFile: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/MSBuild.dll.config
CurrentMSBuildExePath: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/MSBuild.dll
CurrentMSBuildToolsDirectory: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin
VisualStudioInstallRootDirectory: 
MSBuildExtensionsPath: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin

[dbug]: OmniSharp.MSBuild.ProjectLoader
        'CscToolPath' set to '/Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin/Roslyn'
[dbug]: OmniSharp.MSBuild.ProjectLoader
        'CscToolExe' set to 'csc.exe'
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api/MvcProj.Api.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api' on host 1067.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api/MvcProj.Api.csproj
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 491,
  "Command": "/projects"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 492,
  "Command": "/projects"
}
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.Build.resources, Version=15.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.Build.resources.dll'.
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.Build.Tasks.Core.resources, Version=15.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.Build.Tasks.Core.resources.dll'.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api/MvcProj.Api.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api/MvcProj.Api.csproj'
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 492,
  "Command": "/projects",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Cake": {
      "Projects": []
    },
    "DotNet": {
      "Projects": [],
      "RuntimePath": null
    },
    "MsBuild": {
      "SolutionPath": "/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api",
      "Projects": []
    },
    "Script": {
      "Projects": []
    }
  },
  "Seq": 40,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 491,
  "Command": "/projects",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Cake": {
      "Projects": []
    },
    "DotNet": {
      "Projects": [],
      "RuntimePath": null
    },
    "MsBuild": {
      "SolutionPath": "/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api",
      "Projects": []
    },
    "Script": {
      "Projects": []
    }
  },
  "Seq": 39,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 493,
  "Command": "/projects"
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 493,
  "Command": "/projects",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Cake": {
      "Projects": []
    },
    "DotNet": {
      "Projects": [],
      "RuntimePath": null
    },
    "MsBuild": {
      "SolutionPath": "/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api",
      "Projects": []
    },
    "Script": {
      "Projects": []
    }
  },
  "Seq": 51,
  "Type": "response"
}

**Comment by filipw** [comment]
it looks like the problem with wildcards in package references again? This is fixed in newer OmniSharp build. 
try setting `"omnisharp.path": "1.32.19"` and restart again

**Comment by mdmoura** [comment]
@filipw That does not work. I get;

```
Starting OmniSharp server at 5/2/2019, 10:22:08 PM
    Target: /Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api

OmniSharp server started with Mono 5.18.1.
    Path: /Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.19/omnisharp/OmniSharp.exe
    PID: 1810

Cannot open assembly '/Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.19/omnisharp/OmniSharp.exe': No such file or directory.
```

**Comment by filipw** [comment]
try this https://github.com/OmniSharp/omnisharp-vscode/issues/3009#issuecomment-484772057

**Comment by mdmoura** [comment]
@filipw I checked the omnisharp folder and I have two folders: 1.32.19 which is empty and 1.32.18. 
When I change to 1.32.18 in Settings now it starts but still does not work. The log is:

```
Starting OmniSharp server at 5/2/2019, 10:29:11 PM
    Target: /Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api

OmniSharp server started with Mono 5.18.1.
    Path: /Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/OmniSharp.exe
    PID: 1954

[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Cake, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.DotNet, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.DotNetTest, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Host, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.MSBuild, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Roslyn, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Roslyn.CSharp, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Script, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Shared, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null
[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin"
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.Build.Utilities.Core.dll' (name-only).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.Build.Tasks.Core.dll' (name-only).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.Build.Framework.dll' (name-only).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.Build.dll' (name-only).
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.CodeAnalysis.VisualBasic.Workspaces, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll'.
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.CodeAnalysis.VisualBasic.Features, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.CodeAnalysis.VisualBasic.Features.dll'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[dbug]: OmniSharp.MSBuild.ProjectSystem
        MSBuild environment: 
Mode: Standalone
RunningTests: False
RunningInVisualStudio: False
MSBuildToolsDirectory32: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin
MSBuildToolsDirectory64: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin
MSBuildSDKsPath: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks
CurrentMSBuildConfigurationFile: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/MSBuild.dll.config
CurrentMSBuildExePath: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/MSBuild.dll
CurrentMSBuildToolsDirectory: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin
VisualStudioInstallRootDirectory: 
MSBuildExtensionsPath: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin

[dbug]: OmniSharp.MSBuild.ProjectLoader
        'CscToolPath' set to '/Users/MK/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin/Roslyn'
[dbug]: OmniSharp.MSBuild.ProjectLoader
        'CscToolExe' set to 'csc.exe'
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api/MvcProj.Api.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api' on host 1879.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api/MvcProj.Api.csproj
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 98,
  "Command": "/projects"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 97,
  "Command": "/projects"
}
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.Build.resources, Version=15.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.Build.resources.dll'.
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.Build.Tasks.Core.resources, Version=15.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate '/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Microsoft.Build.Tasks.Core.resources.dll'.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api/MvcProj.Api.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api/MvcProj.Api.csproj'
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 98,
  "Command": "/projects",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Cake": {
      "Projects": []
    },
    "DotNet": {
      "Projects": [],
      "RuntimePath": null
    },
    "MsBuild": {
      "SolutionPath": "/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api",
      "Projects": []
    },
    "Script": {
      "Projects": []
    }
  },
  "Seq": 40,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 97,
  "Command": "/projects",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Cake": {
      "Projects": []
    },
    "DotNet": {
      "Projects": [],
      "RuntimePath": null
    },
    "MsBuild": {
      "SolutionPath": "/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api",
      "Projects": []
    },
    "Script": {
      "Projects": []
    }
  },
  "Seq": 39,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 99,
  "Command": "/projects"
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 99,
  "Command": "/projects",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Cake": {
      "Projects": []
    },
    "DotNet": {
      "Projects": [],
      "RuntimePath": null
    },
    "MsBuild": {
      "SolutionPath": "/Users/MK/GD/MvcProj/MvcProj.Project/MvcProj.Project.Source/src/MvcProj.Api",
      "Projects": []
    },
    "Script": {
      "Projects": []
    }
  },
  "Seq": 51,
  "Type": "response"
} 
```

**Comment by filipw** [comment]
yes, but please try `"omnisharp.path": "1.32.19-beta.25"` - thanks

**Comment by mdmoura** [comment]
> try this [#3009 (comment)](https://github.com/OmniSharp/omnisharp-vscode/issues/3009#issuecomment-484772057)

Ok, that worked ... 

In my case it is common Omnisharp to stop working ... Usually during updates.

**Comment by filipw** [comment]
Thanks for confirming 👍
I will close this issue since it's essentially a duplicate of #3009 which is already resolved - you now run on the beta of 1.32.19 of OmniSharp and the stable version will be included in the next extension release which will happen very soon (we just need to merge #3038 first). 

thanks and sorry for the troubles
