### ISSUE TITLE
Fail to get code actions

### ISSUE THREAD

**Issue by ArmaanMcleod** [OmniSharp/omnisharp-vscode#5105]
## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.406
 Commit:    3a48fd6fe5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.406\

Host (useful for support):
  Version: 5.0.15
  Commit:  3065735be7

.NET SDKs installed:
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.212 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
VS Code version:
```
1.65.0
b5205cc8eb4fbaa726835538cd82372cc0222d43
x64
```
C# Extension version: 
```
v1.24.1
```
## OmniSharp log

```
[fail]: OmniSharp.Stdio.Host
        ************  Response (11.9941ms) ************ 
{
  "Request_seq": 1259,
  "Command": "/v2/getcodeactions",
  "Running": true,
  "Success": false,
  "Message": "\"System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.\\r\\n   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)\\r\\n   at System.Reflection.RuntimeAssembly.get_DefinedTypes()\\r\\n   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()\\r\\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\\r\\n   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()\\r\\n   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()\\r\\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\\r\\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\\r\\n   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)\\r\\n   at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects.LoadFrom(Project project) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Refactoring\\\\V2\\\\CachingCodeFixProviderForProjects.cs:line 93\\r\\n   at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects.GetAllCodeFixesForProject(ProjectId projectId) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Refactoring\\\\V2\\\\CachingCodeFixProviderForProjects.cs:line 57\\r\\n   at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.BaseCodeActionService`2.GetSortedCodeFixProviders(Document document) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Refactoring\\\\V2\\\\BaseCodeActionService.cs:line 156\\r\\n   at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.BaseCodeActionService`2.<AppendFixesAsync>d__13.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.BaseCodeActionService`2.<CollectCodeFixesActions>d__12.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Refactoring\\\\V2\\\\BaseCodeActionService.cs:line 123\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.BaseCodeActionService`2.<GetAvailableCodeActions>d__9.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Refactoring\\\\V2\\\\BaseCodeActionService.cs:line 80\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.GetCodeActionsService.<Handle>d__1.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Refactoring\\\\V2\\\\GetCodeActionsService.cs:line 32\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 230\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 131\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Stdio.Host.<HandleRequest>d__14.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:line 218\"",
  "Body": null,
  "Seq": 53207,
  "Type": "response"
}
```

**Comment by lonix1** [comment]
I have this too!

If you try ctrl+. a few times does it eventually work? May be related to https://github.com/OmniSharp/omnisharp-vscode/issues/5085 and https://github.com/OmniSharp/omnisharp-vscode/issues/5091

There are a MANY problems with the newest version. vscode devs, please release a hotfix for https://github.com/OmniSharp/omnisharp-vscode/pull/5089 so we don't have to wait a whole month for the next release. Rolling back is also no good as there were bugs there too, so were excited to upgrade to this release, but now there are new bugs!

**Comment by lonix1** [comment]
@filipw I have the same problem, but my log is:
````
[fail]: OmniSharp.Stdio.Host
        ************  Response (120.3542ms) ************ 
{
  "Request_seq": 379,
  "Command": "/v2/getcodeactions",
  "Running": true,
  "Success": false,
  "Message": "\"System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.\\nCould not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\\n\\nCould not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\\n\\nCould not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\\n\\nCould not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\\n\\nCould not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\\n\\nCould not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\\n\\nCould not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\\n\\nCould not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\\n\\nCould not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\\n\\nCould not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\\n\\nCould not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\\n\\nCould not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, 

  // .......it goes on like this for many 100s of lines.....

  "Body": null,
  "Seq": 3917,
  "Type": "response"
}
````

I am using the dotnet6 build, NOT unity, with `"omnisharp.useModernNet": true, "omnisharp.useGlobalMono": "never""`.

**Comment by ArmaanMcleod** [comment]
@filipw Thanks for providing this. Unfortunately we can't really upgrade .NET 6 SDK just yet. Not really a big issue, I can just do code refactoring through VS for the time being. 

Would be great if upgrades were more backwards compatible, since this was working for me not to long ago. 

Any chance this could get fixed in an upcoming release or is upgrading the only option?

**Comment by jonkelling** [comment]
I just came across this, but the latest suggestion is not working for me. I installed Mono for Windows x64. `useGlobalMono` is no longer available. I set the `monoPath` to `C:\Program Files\Mono`.

**Comment by thewhitewayofdelight** [comment]
Experiencing this issue as well

**Comment by thewhitewayofdelight** [comment]
Months passed already.

Just as Jonkelling said, it works normally on MacOS, but not on Windows. I don't know why...
I tried to use the same C# version and mono version, but still can't make it work on Windows.

**Comment by GrahamMThomas** [comment]
I'm currently experiencing this error after upgrading to .net 8

**Comment by MJLHThomassenHadrian** [comment]
> I'm currently experiencing this error after upgrading to .net 8

Same here! How to fix this? Its pretty annoying.

**Comment by DanteMarshal** [comment]
I get this in Unity.
I get a similar error when developing Asp.Net MVC that includes one or more Razor pages.

The amount of times I've recently spent trying to make intellisense just work is more than I've actually coded anything.
I'm really considering changing my IDE or something.

**Comment by jonkelling** [comment]
A while back there were a few changes, and since then everything has been working better.
1) Visual Studio Code Editor package in Unity has been replaced by Visual Studio Editor package. Make sure you are up to date
2) Make sure to Visual Studio Code is selected, or re-selected in Unity's External Tools Preferences after doing #1. Regenerate project files.
3) Use the latest C# and C# Dev Kit extensions in Visual Studio Code and make sure use modern .net is checked in VS Code settings
4) Use the newest office Unity extension from Microsoft in VS Code.

**Comment by jonkelling** [comment]
> I get this in Unity, trying to load a DLL that I built myself and put right there in unity

Make sure, if you're using assembly definitions, that your .asmdef file has the DLL listed in `precompiledReferences`

**Comment by DanteMarshal** [comment]
> A while back there were a few changes, and since then everything has been working better.
> 
> 1. Visual Studio Code Editor package in Unity has been replaced by Visual Studio Editor package. Make sure you are up to date
> 2. Make sure to Visual Studio Code is selected, or re-selected in Unity's External Tools Preferences after doing # 1. Regenerate project files.
> 3. Use the latest C# and C# Dev Kit extensions in Visual Studio Code and make sure use modern .net is checked in VS Code settings
> 4. Use the newest office Unity extension from Microsoft in VS Code.

Problem solved after installing `visualstudiotoolsforunity.vstuc` vscode extension !
