### ISSUE TITLE
Async Debugging Variable Scope

### ISSUE THREAD

**Issue by matthewjcooper** [OmniSharp/omnisharp-vscode#871]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```
VS Code version: 1.7.1
C# Extension version:1.4.1

I wasn't sure if this was an issue with omnisharp or the docker generator, so i'm posting both places. 

Link to issue on docker project: https://github.com/Microsoft/generator-docker/issues/125

**Details:**
My Web API project is using async methods, and when I use this generator to run the app in the docker container with remote debugging not all variables are in scope in the locals window. The code runs fine if i just continue the execution, but I can't inspect variable values. When I debug the project without the docker container(just locally on my dev machine) all variables show in the locals window.

**Screenshot while debugging through docker:**
<img width="1236" alt="screen shot 2016-11-04 at 1 13 07 pm" src="https://cloud.githubusercontent.com/assets/1433729/20017331/2047c2fa-a291-11e6-8e8a-0f05e72fb10d.png">

**Screenshot of same code debugging locally:**
<img width="1232" alt="screen shot 2016-11-04 at 1 22 05 pm" src="https://cloud.githubusercontent.com/assets/1433729/20017463/b9f21766-a291-11e6-8b2e-20324dd3d5ce.png">

Notice that organization is shown in the locals screen when debugging locally, but not remotely. Also, look at the debug output where i typed in the variable name "organization" and i get the value for the object when debugging local, but not remote. The call stack is different as well. 

The app returns the organization in both instances, but just can't inspect while debugging in docker.

Any help is appreciated.
Thanks!

**Comment by gregg-miskelly** [comment]
@matthewjcooper can you tell me what version of clrdbg you have inside your container? (should be in /clrdbg/version.txt)

**Comment by matthewjcooper** [comment]
Here you go:

```
# cat version.txt
14.0.25520.0 built by: CLRDBG
```

**Comment by matthewjcooper** [comment]
If it helps at all. Since the Call stack looked different as well and i noticed there was another line i could select in the one that is debugging against docker, I selected that line and it looks like there is an exception in the debugger if you look at the locals window, screenshot below. This is in my repository, which is using entity framework async methods, with the mysql provider: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

<img width="1226" alt="screen shot 2016-11-04 at 5 03 48 pm" src="https://cloud.githubusercontent.com/assets/1433729/20023886/e0c02b34-a2b0-11e6-855a-4fc071cc4ab1.png">

**Comment by matthewjcooper** [comment]
So I noticed a fresh new aspnet app with async methods debugged just fine. So i slowly added stuff from my project to see when i broke. After several hours, i noticed that it was a sub folder of code that had about 350 files (was a subset of the [nHapi](https://github.com/duaneedwards/nHapi) library, that was cleaned up to run under .net core).

For kicks i moved this subset of files into it's own project and then the debugger started working again as expected. 

Do you think this is something to do with a large amount of files in a given assembly, causing the issue?

**Comment by gregg-miskelly** [comment]
@matthewjcooper my _guess_ is that there is something in the set of files you added that confuses the expression evaluator. Though this is just a guess, and it could just be some sort of straight scale issue that we hadn't noticed before.

**Comment by matthewjcooper** [comment]
Yeah, weird. The expression evaluator doesn't have a problem with the code in the new project, but only while it was in the root project. I can step into it just fine still. Unfortunately i can't really share the project code to allow you to test. I'll try and come up with a reproducible set of code for you in the next few days without my proprietary portions.

**Comment by matthewjcooper** [comment]
This issue has gone away after upgrading to 1.5.x. Any reason you think this might be? Could it be related these two items in the release notes?

> Debugger
> 
> Remote debugging is now supported for attach by using the pipeTransport launch.json option.
> Resolved issue with setting breakpoints when there are multple files with the same name (e.g. two 'Program.cs' files).

**Comment by gregg-miskelly** [comment]
@matthewjcooper it wouldn't have been either of those items. We did however at the same time fix the GetClrdbg.sh script to pull a more recent version of the debugger into the container. My guess is that is what fixed it. Though I can't tell you exactly what change in there resolved the issue.

Glad to hear it is resolved though. Should we close this?

**Comment by matthewjcooper** [comment]
Yup, ran all day and today without this issue.

Thanks!

**Comment by Thaina** [comment]
I think I still experience this. This issue should kept opened

**Comment by gregg-miskelly** [comment]
@Thaina if you are hitting into a problem, please open a new issue so we can try and help.
